### ISSUE TITLE
Add some raster data (not 3338) layer to GeoNode

### ISSUE THREAD

**Issue by BobTorgerson** [ua-snap/snap-arctic-portal#2]
Add any raster data layer that would work well in the Arctic base layer projection to start our exploration of potential data layers.

**Comment by brucecrevensten** [comment]
I got a few different rasters in.  There's a standard range of tricks we're going to need to be aware of when doing this:
- nodata values are weird and transparency is going to be a thing we need to deal with and have good tooling around
- QGIS is a good way to do most of the things we need to do with GDAL, but with a convenient GUI.

**Comment by brucecrevensten** [comment]
After doing a direct upload of this layer:
http://ckan.snap.uaf.edu/dataset/land-cover-v0-4

It loads OK but has a white border.  I’ll check the image out in QGIS to see what the deal is.  Looking at QGIS, it seems to show 0 as white, is that right?  Gdalinfo confirms it: there is a colortable (which is why I didn’t need to apply the color as a style apparently) and 0 is set to rgba(255,255,255,255).  Not sure why that is, so I emailed the team.

Two choices come to mind: modify it to have a real NODATA, or, create a SLD in GeoServer to paint white as transparent.  I’ll try the SLD first, keeping to the principle of “don’t touch the data.”  I referred to this page:

http://docs.geoserver.org/latest/en/user/styling/sld-cookbook/rasters.html#alpha-channel

Well, it looks like either we have to go whole-hog and put the whole style layer in (just switching one value to transparent made the whole thing transparent) — but, this looks like the right way to get a legend in place, so let’s do it.  Can we use rgba(r,g,b,a) as a color target?  …probably not, when I tried it it didn’t understand the legend.

What about using QGIS to make this easier?  It looks like I can create a good colortable there (with labels) but 0 is still treated as data (i.e. needs a label, can’t be transparent).

And, now I see that there’s a bit of confusion: 0 means “not modeled”, which includes both water as well as certain other areas (mountains, it looks like).

After creating the labels and saving the layer as an SLD in QGIS, it took a bit more cleanup to work: QGIS saves things with “paletteEntry” instead of “ColorMapEntry” and uses “value” instead of “quantity.”  Doing that, and setting ColorMap(type=“values”).  That works!

**Comment by brucecrevensten** [comment]
Next up:
http://ckan.snap.uaf.edu/dataset/slope-complexity

First I was confused that the data seemed like it should be other than boolean, but wrong; read the metadata, Bruce!

Uploading into default GN produced black-border/white center, so we need to edit the styling.  Can I succeed just using the built-in style editor?  Layer > Edit Layer > Edit Style.  OK, after some fiddling that didn’t quite get me all the way there — the nodata value is wrong (?) and the color is doing a ramp, which isn’t right.

Gdalinfo shows that the nodata value is real and assigned:

```
  NoData Value=-3.39999999999999996e+38
```

How to make GeoServer understand?  I can try adding another color value and making it transparent as a style, for one thing.  I learned a different technique that will work well here, too: by making the colormap type “values,” it ignores pixels that don’t have any of the listed values.  By listing only the ones we want painted, we can ignore the nodata issue.

```
            <sld:ColorMap type="values">
```

This worked well.  Peculiarly, I can’t get this layer to actually display within MapLoom.  It always says the layer is disabled.  Fine, but I’ll need to loop back to this at some point.
