### ISSUE TITLE
Isolate GeoServer/MapVenture test harnesses

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#48]
- Configure 3 layers (3338 baselayer, raster overlay, vector overlay)
- Capture database backup
- Modify DB backup to point to correct URLs
- Frontend: capture giant JSON-ball of configuration that GeoNode passes to MapVenture, use as static harness for development

**Comment by cstephen** [comment]
What did we decide the "correct URLs" should be? Is the idea to design a `sed` command that will make the database backups relative, so we can move backups back and forth between production and development instances?

**Comment by cstephen** [comment]
I have a backup of base, raster, and vector layer examples + combined map example, corresponding "big ball of JSON", and base layer code snippet to add to `local_settings.py`. I'm going to wait until our next sprint meeting before committing them to the `vagrant-geonode` repo since we might be going in a radically different direction.

**Comment by brucecrevensten** [comment]
To finish this: modify DB import script to allow user to define the URL (default to localhost like we use on development VMs).  Ignore the part about static JSON harness because we'll do that with a new GeoNode API endpoint.
