### ISSUE TITLE
Chat with Peter regarding NCEP data utilization

### ISSUE THREAD

**Issue by brucecrevensten** [ua-snap/snap-arctic-portal#52]

**Comment by BobTorgerson** [comment]
Spoke to Peter regarding issues I was seeing, but he has not had similar problems with his data as he primarily uses the NetCDF data directly, and does not convert them to another format for display on a map. He uses tools like NCL and GrADs for his work primarily. He did point me at some other data that might be of some use to us at: http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.html

**Comment by BobTorgerson** [comment]
Good afternoon Peter,

As part of a project that I'm working on with Bruce Crevensten and John Walsh, I'm trying to make use of the data coming from NCEP, specifically their data on historical air temperature. While working with this data, I've run into a few snags, and John had suggested you use this data regularly in your work, so would be a good source for a couple of questions I had.
1. How do you make use of the NetCDF data? Have you done something like a gdal_translate to create a GeoTIFF image out of this data in a given projection? I've tried translating the NCDF to EPSG: 4326, and while it looks OK at certain places, it fails after passing beyond the Atlantic Ocean west of the Prime Meridian. I've added an image of what that looks like:

< PICTURE HERE>

I really have no idea what is going on here, but I was hopeful you might have bumped against this type of issue in the past with this or other geospatial data. If not, just having an idea how you make use of the NCEP data would be helpful to me.
1. Do you know how to automate the task of collecting the data from the website? I can see that entering the information in the form relates to the URL in a standard GET request to the website, but does not relate to what the name is of the resulting NetCDF file that we would be looking to access. I can programmatically request that the particular NetCDF file be populated, but I do not see a way to access the NetCDF file without knowing the name of the resulting NetCDF file. Do you normally go through the process of getting the data you need from the form?

When you have the time to look at this, I'd be happy to meet with you in person if you would like. I'm can come up to your office if that is most convenient.

Thank you,

Bob Torgerson

**Comment by BobTorgerson** [comment]
Hi Bob,

Generally I use NCL or GrADS to directly visualize netcdf data as those software packages are pretty good at handling the idiosyncrasies of that file type. Those two software packages wouldn't be good at producing GeoTIFF images though.

I haven't had too much trouble downloading the files I need from http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.html, but I haven't had to do too much mass downloading of multiple files. Are you looking to download the entire data set?

**Comment by BobTorgerson** [comment]
Hey Peter,

Thanks for the quick response! 

I have looked at the data in NCL, and it all looks good to me, along with QGIS after I've translated it into a different projection, so I imagine that it must have something to do with GeoServer / OpenLayers displaying the data incorrectly. Since we are trying to make this data web-accessible through a Javascript library for displaying geospatial data, I have had to find a format which can take the NetCDF data and make it available through GeoServer. I went with GeoTIFFs as many people suggest that as a good format for raster data coming from similar NetCDF files. I'll just need to do some more research on what I must be doing incorrectly when trying to incorporate this data into OpenLayers.

Are you looking to download the entire data set?

No, John would like us to have a rolling subset of the data. Something like the average temperature from 2 days ago, a week ago, and a month ago for instance. However, in that scenario, we would want to have a programmatic way of collecting the new data that appears on the website. Since the data we want changes on a day-by-day basis, we would need to know how to get the new data to make it accessible from the web GUI. I think this portion of the website that you sent to me may have the answer, I'm going to have to dig deeper into it to see if I can find a way to automate the download of the data. 

Thanks,

Bob
